# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Fq9J-qekM_is6jeZtYXY4RMmbS2Xmx2
"""

#description: A simple Expense Tracker

#import libraries
import pandas as pd
import numpy as np
from datetime import date

#Create empty lists
Goods_or_servies = []
Prices = []
Dates = []
Expense_types = []

#Create a function to add the expenses to the lists & organize the data

def add_expense(good_or_service, price, date, expense_types):
  GOODS_OR_SERVICE.append(good_or_service)
  PRICE.append(price)
  DATE.append(date)
  EXPENSE_TYPES.append(expense_types)

#main program

option = -1 #This will be the users option, choice or input
while option != 0:
  #create option menu
  print("Welcome to the simple expense tracker: ")
  print("1. Add a food expense")
  print("2. Add Household expense")
  print("3. Add Transportation expense")
  print("4. Show & save the expense report")
  print("0. Exit the program")

  option = int(input("Enter an option\n"))

  #print new line
  print()

  #check for the user input
  if option == 0:
    print("Exiting the program!")
    break
  elif option == 1:
    print("Adding food")
    Expense_types = "FOOD"
  elif option == 2:
    print("Adding household")
    Expense_types = "HOUSEHOLD"
  elif option == 3:
    print("Adding transportation")
    Expense_type = "TRANSPORTATION"
  elif option == 4:
    #create a dataframe and add the expenses
    expense_report = pd.Dataframe()
    expense_report["GOODS_OR_SERVICES"] = GOODS_OR_SERVICES
    expense_report["PRICES"] = PRICES
    expense_report["DATES"] = DATES
    expense_types["EXPENSE_TYPES"] = EXPENSE_TYPES

    #SAVE THE EXPENSE REPORT
    expense_report.tocsv("expenses.csv")

    #show the expense report
    print(expense_report)
  else:
    print("You entered an Invalid choice. Please choose 0, 1, 2, 3 or 4")

    #Allow the user to enter the good or service and the price
    if option == 1 or option == 2 or option == 3:
      good_or_service = input('Enter the good or service for the expense type "+expense_type+" :\n')
      today = date.today()
      add_expense(good_or_service, price, today, expense)

    #print a new line
    print()

